# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cecda64b0d2d39676a7f75b778b36d487603af5ed7087df4877ed839ad1e9437006099a88f7988d0a06cb73b70747d82b6879713898bc15e57cbdfa5b880eb13

test:
  secret_key_base: e132f5db56a3b964ed1c7c2b15dd811ecdbd0afd7266226c8d1230286a39e2ee91bc6a0c41f41761108fec34ceb030879d7cde7101090814cd226bea195a32e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
